services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:3000:3000"
    restart: always
    depends_on:
      - engine
    networks:
      - mendai-network

  engine:
    build:
      context: ./backend
      dockerfile: engine/Dockerfile
    ports:
      - "127.0.0.1:8000:8000"
    env_file:
      - ./backend/engine/.env
    command: uvicorn engine.main:app --host 0.0.0.0 --port 8000
    restart: always
    depends_on:
      - patient_data
      - medical_imaging
      - biomedical_llm
    networks:
      - mendai-network

  patient_data:
    build:
      context: ./backend
      dockerfile: patient_data/Dockerfile
    ports:
      - "127.0.0.1:8001:8001"
    env_file:
      - ./backend/patient_data/.env
    command: uvicorn patient_data.main:app --host 0.0.0.0 --port 8001
    restart: always
    networks:
      - mendai-network

  medical_imaging:
    build:
      context: ./backend
      dockerfile: medical_imaging/Dockerfile
    ports:
      - "127.0.0.1:8002:8002"
    env_file:
      - ./backend/medical_imaging/.env
    command: uvicorn medical_imaging.main:app --host 0.0.0.0 --port 8002
    restart: always
    networks:
      - mendai-network


  biomedical_llm:
    build:
      context: ./backend
      dockerfile: biomedical_llm/Dockerfile
    ports:
      - "127.0.0.1:8003:8003"
    env_file:
      - ./backend/biomedical_llm/.env
    command: uvicorn biomedical_llm.main:app --host 0.0.0.0 --port 8003
    restart: always
    networks:
      - mendai-network

networks:
  mendai-network:
    driver: bridge 